name: evostream
description: "A simple yet powerful interval timer with nested groups and reps"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  material_color_utilities: ^0.11.1
  sqflite_common_ffi: ^2.4.0+2
  flutter_soloud: ^3.4.9
  wakelock_plus: ^1.4.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  golden_screenshot: ^9.1.2

flutter:
  uses-material-design: true

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
        style: italic
        weight: 100
      - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        style: italic
        weight: 200
      - asset: assets/fonts/poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        style: italic
        weight: 300
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
        style: italic
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        style: italic
        weight: 600
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        style: italic
        weight: 800
      - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        style: italic
        weight: 900