name: evostream
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  material_color_utilities: ^0.11.1
  sqflite_common_ffi: ^2.4.0+2
  flutter_soloud: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
